In [ ]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [ ]:
df = pd.read_csv("pib.csv")

In [ ]:
df['Country Name'].head()

0         Aruba
1           NaN
2    Afganistán
3           NaN
4        Angola
Name: Country Name, dtype: object

In [ ]:
america = [
    'Antigua y Barbuda', 'Argentina', 'Bahamas', 'Barbados',
    'Belice', 'Bolivia', 'Brasil', 'Canadá', 'Chile',
    'Colombia', 'Costa Rica', 'Cuba', 'Dominica', 'Ecuador',
    'El Salvador', 'Estados Unidos', 'Granada', 'Guatemala',
    'Guyana', 'Haití', 'Honduras', 'Jamaica', 'México', 'Nicaragua',
    'Panamá', 'Paraguay', 'Perú', 'República Dominicana',
    'San Vicente y las Granadinas', 'Santa Lucía', 'Suriname',
    'Trinidad y Tobago', 'Uruguay', 'Venezuela'
]

df_america = df[df["Country Name"].isin(america)]

In [ ]:
df_america.head(10)

,Unnamed: 0,Country Name,Country Code,1961,1962,1963,1964,1965,1966,1967,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
9,9,Argentina,ARG,5.427843,-0.852022,-5.308197,10.130298,10.569433,-0.659726,3.191997,...,-2.080328,2.818503,-2.617396,-2.000861,-9.900485,10.441812,6.020745,-1.855788,-1.342931,4.367333
12,12,Antigua y Barbuda,ATG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.120368,2.712727,6.712005,3.172222,-18.868777,8.172863,8.497763,3.865502,2.540442,4.998040
23,23,Bahamas,BHS,10.667097,10.451972,10.524055,10.501567,10.425596,9.071929,9.598114,...,-1.156508,3.371399,2.397955,-0.838586,-20.089366,17.586139,10.877901,3.048242,3.378666,NaN
26,26,Belice,BLZ,4.892277,4.892652,4.956434,4.999880,4.930541,4.770845,4.913123,...,-0.018741,-1.833237,0.822069,4.256587,-13.522900,17.989924,9.250513,0.500128,3.504664,2.748317
28,28,Bolivia,BOL,2.089296,5.578918,6.797626,3.956597,4.913442,7.170590,6.317220,...,4.263921,4.195206,2.868084,1.506721,-12.719469,10.029049,3.747418,2.516366,-1.123356,-1.582376
29,29,Brasil,BRA,8.600000,6.600000,0.600000,3.400000,2.400000,6.700000,4.200000,...,-3.275917,1.322869,1.783667,1.220778,-3.276759,4.762604,3.016694,3.241655,3.419315,2.285746
30,30,Barbados,BRB,7.696530,9.060759,-5.078421,5.004876,11.434843,4.003371,10.636136,...,1.416324,0.654656,-0.252085,0.241100,-17.405931,8.019877,15.945321,1.814198,3.366949,2.700000
35,35,Canadá,CAN,3.163292,7.427837,5.297440,6.656000,6.317200,6.759690,3.065421,...,1.038551,3.033835,2.742963,1.908432,-5.038233,5.950528,4.695420,1.953086,2.046266,1.742685
39,39,Chile,CHL,5.519611,3.930785,5.686672,2.461134,0.670839,11.463422,3.588111,...,1.753039,1.357695,3.990029,0.644223,-6.139697,11.337403,2.063919,0.677025,2.805126,2.459255
45,45,Colombia,COL,5.089217,5.411890,3.286708,6.166941,3.600011,5.236736,4.134864,...,2.087383,1.359361,2.564324,3.186855,-7.185914,10.801198,7.328277,0.841820,1.493307,2.642015

In [ ]:
df_america.shape
print('Tenemos 34 filas y 68 columnas')

Tenemos 34 filas y 68 columnas

In [ ]:
df_america.dtypes

Unnamed: 0        int64
Country Name     object
Country Code     object
1961            float64
1962            float64
                 ...
2021            float64
2022            float64
2023            float64
2024            float64
2025            float64
Length: 68, dtype: object

In [ ]:
def calcular_completitud(df_america):
    completitud = pd.DataFrame(df_america.isnull().sum()).reset_index()
    completitud = completitud.rename(columns={"index": "columna", 0: "faltantes"})
    completitud["completitud"] = (1 - completitud["faltantes"] / df_america.shape[0]) * 100
    completitud = completitud.sort_values(by="completitud", ascending=True)
    completitud.reset_index(drop=True, inplace=True)
    return completitud.round(0)

## Debido a que no pude quitar los null, los dejamos ya que no causa una molestia para los graficos